H2Blog/urls.py
"""H2Blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views - İşlev görünümleri
    1. Add an import:  from my_app import views --> 1. Bir içe aktarma ekleyin: my_app içe aktarma görünümlerinden
    2. Add a URL to urlpatterns:  path('', views.home, name='home') --> v  
Class-based views - Sınıf tabanlı görünümler
    1. Add an import:  from other_app.views import Home --> 1. Bir içe aktarma ekleyin: other_app.views import
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home') --> 2. urlpatterns'e bir URL ekleyin: path ('', Home.as_view (), name = 'home')
Including another URLconf - Başka bir URLconf dahil
    1. Import the include() function: from django.urls import include, path -->  1. include () işlevini içe aktarın: django.urls dizininden import include, path   
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls')) --> 2. urlpatterns’e bir URL ekleyin: path ('blog /', include ('blog.urls'))   
"""
   
from django.contrib import admin 
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

from article import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    
    # Eğer bana 'articles' şeklinde bir kalıp gelirse sen başka bir 'url' dosyasını buraya dahil et ve sonuna o 'url' deki yazılanları da dahil et.
    # Yani 'articles'uydulamasının içindeki "article.urls" dosyasını buraya include et. Tabi bu include'u yukarıda import etmemiz de gerekiyor
    # Bunu yapmaktaki maksat daha fazla url adresinin bu sayfaya yığılamasını engellemek
    path('articles/',include("article.urls")),
    
    # user uygulamasının url bağlantısı;
    path('user/', include("user.urls")),
    
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
# H2Blog / article / urls.py
# Bu url sayfasını yapmaktaki maksat daha fazla url adresinin ana dizindeki url sayfasına yığılamasını engellemek

from django.contrib import admin
from django.urls import path

# Şu anki klasördeki views'i al
from . import views 

# Bu uygulamamıza isim vermemiz önemli.
# Çünkü daha sonra 'redirect' işlemi yaptığımız zaman şu uygulamanın içindeki url'ye göre 'redirect' yap diyeceğiz
app_name = "article"

# article içindek bir tane url uygulamamızı tanımladık.
urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
    
]

user/urls.py
# H2Blog / user / urls.py
# Bu url sayfasını yapmaktaki maksat daha fazla url adresinin ana dizindeki url sayfasına yığılamasını engellemek

from django.contrib import admin
from django.urls import path

# Şu anki klasördeki views'i al
from . import views 

# uygulamamızın adı: 
app_name = "user"

urlpatterns = [
    path('register', views.register,name="register"),
    path('login/', views.loginUser,name="login"),
    path('logout/', views.logoutUser,name="logout"),
    
      
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here. (Modellerinizi burada oluşturun.)

# Article'ları yani makaleleri oluşturmak için; 
class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name ="Yazar")
    title = models.CharField(max_length= 50,verbose_name ="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name ="Oluşturma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    
# Yönetim panelinde article'ların ismini göstermek için;
    def __str__(self): 
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']    

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required

# Create your views here.(Görüşlerinizi burada oluşturun.)
# Buradaki url map'ine göre çalışacak fonksiyonlarımızı barındıran dosya.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    
    return render(request,"articles.html",{"articles":articles})



def index(request):
    return render(request,"index.html")


def about(request):
    return render(request,"about.html")


@login_required(login_url = "user:login")

def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)


@login_required(login_url = "user:login")

def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu")
        return redirect("article:dashboard")
        

    return render(request,"addarticle.html",{"form":form})


def detail(request,id):
    # article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()

    return render(request,"detail.html",{"article":article,"comments":comments})



@login_required(login_url = "user:login")

def updateArticle(request,id):
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi")
        return redirect("article:dashboard")
    
    return render(request,"update.html",{"form":form})


@login_required(login_url = "user:login")

def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard")


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author  = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}
  
<h3>Hakkımda</h3>
<hr>
<p>
    Merhaba;
<br>
Ben Haluk Haçkalı. Fırsat buldukça motosikletle yolculuklara çıkan ve kamplar yapan bir ortaokul öğretmeniyim. Okuldan arta kalan zamanlarımda web tasarım, grafik tasarım, 3d model tasarımı yapmaktayım. Bilgisayara bilimlerine genel bir ilgimin olamasına rağmen uzmanlaştığım bir b alan bulunmamakta. Uğraşlarım hobi düzeyinde, amatör seviyededir. 
<br>
Seyahatlerimin fotoğraflarını yayınlayıp, yazılar yazmaktayım. Kendi tecrübelerimi ve diğer insanlardan öğrendiğim bilgileri paylaşıyorum. Çeşitli alanlarda internet siteleri yönetiyorum. 
<br>
Bu blogu tamamen kişisel amaçla kurdum. Bu blogun hizmet amacı; yönettiğim sitelerin tanıtımını yapmak ve zaman zaman gelen blog yazma isteğine cevap vermek.<br> 

<br>
*Kişisel hobilerimi birkaç ana başlık altında toplayacak olursam;<br>
   1. Motosiklet ve motosiklete dair her şey,<br>
   2. Bilgisayar bilimi (web tasarım, çizim, video edit vb),<br>
   3. Model uçak yapımı,<br>
   4. Doğa yürüyüşü ve kamp<br>
<br>
*Amatör Seviyede Kullandığım Programlar ve Uygulamalar;<br> 
  1. Davinci Resolve<br>                     
  2. Blender 2.80<br>
  3. Krita <br>
  4. Kdenlive<br> 
  5. SketchBook<br>
  6. Inkscape<br>
  7. Shotcut<br>
  8. Gimp 2.10.8<br>
  9. Joomla!<br>
  10. WordPress
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            
            {% csrf_token %}
            {{ myform.media }}
            {{form.media}}
            
            {{form|crispy}}
            
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Ekle</button>
        </form>
    </div>
  </div>



{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<!--  MAKALELER SAYFA BAŞLIĞI  -->
<div class="row">
    <div class="col-md-12 offset-md-3">
        <div class="col-lg-8">
            <h2>Makaleler</h2>
            <hr>
        </div>
    </div>
</div>

<!--  ARAMA FORMU -->
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder=" Ara...">
                <button type="submit" class="btn btn-outline-info">Ara</button>
            </form>
      </div>
    </div>
</div>


<!--  MAKALELER  -->
{% if articles %}

{% for article in articles  %}
<div class="row">
    <div class="col-md-12 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

    <!-- Title -->
    <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>

    <!-- Author -->
    <p class="lead">
        
        {{article.author.username}} tarafından yayınlandı
    </p>

    <hr>

    <!-- Date/Time -->
    <p>{{article.created_date}}</p>

    <hr>

    <!-- Preview Image -->
    {% if article.article_image %}
    <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
    {% endif %}
     

    <!-- Post Content -->
    <p class="lead">
        {{article.content|safe|truncatewords:50}}
    </p>

    <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Devamını Oku</a>
    <br>
    <br>
    <hr>
   
    </div>
    </div>
</div>  

{% endfor %}


{% else %} 

<!-- MAKALE BULUNAMDI ALLERT'İ -->
<div class ="row"> 
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <div class = "alert alert-danger">Makale Bulunamadı</div>
        </div>
    </div>
</div>

{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-success" href = "/articles/addarticle">Makale Ekle </a>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
        <td>{{article.author.username}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="/articles/update/{{article.id}}" class = "btn btn-danger">Güncelle</a></td>
        <td><a href="/articles/delete/{{article.id}}" class = "btn btn-danger">Sil</a></td>
          
      </tr>
      {% endfor %}
                               
    </tbody>
  </table>
  
  {% else %}

  <div class = "alert alert-danger">Henüz bir makaleniz bulunmuyor... </div>
      
  
  {% endif %}
  
  {% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{article.title}}</h3>

      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe}}
      </p>
      

      <hr>
      <h4>Yorumlar</h4>
      <hr>
      {% if comments %}
      {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="https://sun9-57.userapi.com/c624522/v624522496/1bc67/eBRDf6x60X0.jpg?ava=1" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
      {% endfor %}
      
      
      {% else %}
      <div class ="alert alert-danger">
        Bu makaleye herhangi bir yorum yazılmamış, ilk yorumu yapabilirsiniz!
      </div>
      {% endif %}
      



      <div class="card my-4">
        <h5 class="card-header">Yorum Ekle:</h5>
        <div class="card-body">
          <form method = "post" action = "{% url 'article:comment' article.id %}">
            {% csrf_token %}

            <div class="form-group">
              <label for="formGroupExampleInput">İsim</label>
              <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Lütfen İsminizi Giriniz...">
            </div>
            


            <div class="form-group">
              <label for="formGroupExampleInput">Yorum</label>
              <textarea name = "comment_content" class="form-control" rows="3"></textarea>
            </div>
            <hr>
            <button type="submit" class="btn btn-primary">Gönder</button>
          </form>
        </div>
      </div>

    </div>
    
    

    
  </div>
  

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
    <h3>H2Blog - Haluk Haçkalı Kişisel Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.</p>
</div>

<p>
        {% if request.user.is_authenticated %}
                Giriş Yapılmış, {{request.user.username}}
        {% else %}
                Giriş Yapılmamış
        {% endif %}

</p>
  
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>H2Blog</title>
</head>
<body>
        {% include "includes/navbar.html" %}

        

        <div style="margin-top: 80px; margin-bottom: 100px;" class="container">

                      

            
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
        
                {% endif %}
            {% block body %}
    
            {% endblock body %}

        </div>


    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

        
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}  
  
  
  <div class="row">
    <div class="col-md-6 offset-md-3">

    <h3>Giriş Yap</h3>
    <hr>
    <form method = "post">

      {% csrf_token %} 
      {{form|crispy}}
      <br>
      <button type="submit" class="btn btn-primary">Giriş Yap</button>
    
    </form>
    </div>
  
  </div>
  
{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}  
  
  
  <div class="row">
    <div class="col-md-6 offset-md-3">

    <h3>Kayıt Ol</h3>
    <hr>
    <form method = "post">

      {% csrf_token %} <!-- Giriş güvenliği iin ekliyoruz.-->
      {{form|crispy}}
      <br>
      <button type="submit" class="btn btn-primary">Giriş Yap</button>
    
    </form>
    </div>
  
  </div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Güncelle</button>
        </form>
    </div>
  </div>


{% endblock body %}